---
title: Volgende klant alsjeblieft
hero_image: images/banner.png
description: Een winkel simulatie project waar de klant voorwerpen kan kopen.
meta_title: Scratch-programmeerprojecten voor kinderen en tieners | Volgende klant alsjeblieft
meta_description: Leer Scratch met de programmeerprojecten van de Raspberry Pi Foundation voor kinderen en tieners. Maak een Scratch-app waar de klant voorwerpen kan kopen.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: What you will make
  - 
    title: Your shop
  - 
    title: Producten te koop
    completion:
      - engaged
  - 
    title: Aankopen
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: Share
  - 
    title: What next?
