---
title: Volgende klant alsjeblieft
hero_image: images/banner.png
description: Een winkel simulatie project waar de klant voorwerpen kan kopen.
meta_title: Scratch coding projects for kids and teens | Next customer please
meta_description: Learn Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch app where the customer can buy items from your shop.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: You will make
  - 
    title: Jouw business idee
  - 
    title: Producten te koop
    completion:
      - engaged
  - 
    title: Aankopen
  - 
    title: Extra functies
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Verbeter je project
  - 
    title: Deel
  - 
    title: Wat kun je verder nog doen?
