otitle: design-project-template
hero_image: images/banner.png
description: design-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Your business idea
  - title: Items for sale
  - title: Paying
  - title: Additional features
  - title: Share
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
