---
title: Next customer please
hero_image: images/banner.png
description: A shop simulation project where the customer can buy items.
meta_title: Scratch coding projects for kids and teens | Next customer please
meta_description: Learn Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch app where the customer can buy items from your shop.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: What will you make?
  - title: Your shop
  - title: Items for sale
    completion:
      - engaged
  - title: Purchases
  - title: Additional features
    completion:
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Challenge
    challenge: true
  - title: Share
  - title: What next?
