---
title: Cwsmer nesaf plîs
hero_image: images/banner.png
description: Prosiect sy'n creu efelychiad o siop lle mae cwsmeriaid yn gallu prynu eitemau.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Byddi di'n creu
  - title: Dy syniad busnes
  - title: Eitemau ar werth
    completion:
      - engaged
  - title: Prynwyd
  - title: Nodweddion ychwanegol
    completion:
      - internal
  - title: Cwis cyflym
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Uwchraddio dy brosiect
  - title: Rhannu
  - title: Beth nesaf?
