---
title: Cwsmer nesaf plîs
hero_image: images/banner.png
description: Prosiect sy'n creu efelychiad o siop lle mae cwsmeriaid yn gallu prynu eitemau.
meta_title: Scratch coding projects for kids and teens | Next customer please
meta_description: Learn Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch app where the customer can buy items from your shop.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: Byddi di'n creu
  - 
    title: Dy syniad busnes
  - 
    title: Eitemau ar werth
    completion:
      - external
  - 
    title: Prynwyd
  - 
    title: Nodweddion ychwanegol
    completion:
      - internal
  - 
    title: Cwis cyflym
    knowledge_quiz:
      path: cwis1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - internal
  - 
    title: Uwchraddio dy brosiect
  - 
    title: Rhannu
  - 
    title: Beth nesaf?
