---
title: Client suivant, s'il vous plaît
hero_image: images/banner.png
description: Un projet de simulation de boutique où le client peut acheter des articles.
meta_title: Scratch coding projects for kids and teens | Next customer please
meta_description: Learn Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch app where the customer can buy items from your shop.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Ton idée commerciale
  - 
    title: Articles en vente
    completion:
      - engaged
  - 
    title: Achats
  - 
    title: Fonctionnalités supplémentaires
    completion:
      - internal
  - 
    title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Partager
  - 
    title: Et ensuite ?
